spring:
  cloud:
    config:
      uri:
      - http://localhost:8888/application/{profile}   
        
         
  application:
    name: department-service 
server:
  port: 8801         
  
  